#!/bin/sh
# -*- mode: sh, coding: utf-8 -*-
if [ $# -lt 1 ]
then
    echo "Serves the tutorial using twistd (daemonized)."
    echo ""
    echo "Call with 'start' to start serving, and with 'stop' to stop."
    echo ""
    echo "Usage: $0 [start|stop]"
    exit
fi

case "$1" in

start) 	twistd web --path=doc/tutorial &&\
	echo "Tutorial server started at port 8080..."
	;;
stop)	kill `cat twistd.pid` && rm twistd.log &&\
        echo "Tutorial server stopped..."
	;;

esac