#!/bin/sh
# -*- mode: sh, coding: utf-8 -*-
if [ $# -lt 1 ]
then
    echo "Serves the tutorial using twistd (daemonized)."
    echo ""
    echo "Call with 'start' to start serving, and with 'stop' to stop."
    echo ""
    echo "Usage: $0 [start|stop]"
    exit
fi

DIR="$( cd "$( dirname "$0" )" && pwd )"

case "$1" in

start) 	twistd --pidfile $DIR/tutorial.pid \
               --logfile $DIR/tutorial.log \
               web --path=$DIR/tutorial && \
	echo "Tutorial server started at port 8080..."
	;;
stop)	if [ -f $DIR/tutorial.pid ]
	then
	    kill `cat $DIR/tutorial.pid` && \
            rm $DIR/tutorial.log && \
            echo "Tutorial server stopped..."
	else
	    echo "Couldn't find pidfile, aborting..."
	fi
	;;
esac

